server:
  port: 8081

# Spring Boot Dependencies
springBootVersion: 2.7.15
springCloudVersion: 2021.0.6
springDependencyManagerVersion: 1.1.0

spring:
  application:
    name: StamperTestApplication

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

stamper-service:
  url: http://localhost:8081

multipart:
  enabled: true
  max-file-size: 10MB
  max-request-size: 10MB


# Other application-specific properties can be added here
